version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: autoslip_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    build: .
    restart: always
    depends_on:
      - db
    volumes:
      - ./.env:/app/.env
      - ./credentials.json:/app/credentials.json
    # นำ .env โยนเข้าไปใน Container ด้วย
    env_file:
      - .env
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com    # ใช้อีเมลนี้ล็อกอินเข้าเว็บ (เปลี่ยนได้)
      PGADMIN_DEFAULT_PASSWORD: password1234    # ใช้รหัสผ่านนี้ล็อกอินเข้าเว็บ (เปลี่ยนได้)
    ports:
      - "5050:80"                               # เราจะเข้าเว็บผ่านพอร์ต 5050
    depends_on:
      - db

volumes:
  pgdata: